### ISSUE TITLE
Add `repr.Dump` convenience function

### ISSUE THREAD

**Issue by zx8** [mitranim/repr#2]
This would be a lot easier to type (and familiar to those coming from [go-spew](https://github.com/davecgh/go-spew)) to remember than the current:

```
fmt.Println(repr.String(...))
```

(I don't mind what the name is, `Dump` was just an example)

Thanks for a great package!

**Comment by mitranim** [comment]
Thanks for the suggestion. This didn't exist because I always used an editor snippet and didn't want the library to generate errors (other than panics... mighty logic), but I can see the convenience.

Went with `Println` and `PrintlnC` for consistency with `fmt`. Let me know if you want any more tweaks. 🙂

(Edit: and glad you're finding this useful. 🙂)

**Comment by zx8** [comment]
Thank you!
